### Consulta de cursos
GET http://api.controlasistenciasexto/cursos

### Consulta de cursos por id
GET http://api.controlasistenciasexto/cursos/1

### Modificar Curso
PUT http://api.controlasistenciasexto/cursos/1 
Content-Type: application/json

{
  "nombre_curso": "Curso de ejemplo",
  "nivel": "Nivel de ejemplo",
  "paralelo": "Paralelo de ejemplo"
}

### Adicionar Curso
POST http://api.controlasistenciasexto/cursos
Content-Type: application/json

{
  "nombre_curso": "Curso de ejemplo",
  "nivel": "Nivel de ejemplo",
  "paralelo": "Paralelo de ejemplo"
}

### Eliminar Curso
DELETE http://api.controlasistenciasexto/cursos/1