### Consulta de estudiantes
GET http://api.controlasistenciasexto/estudiantes

### Consulta de estudiante por id
GET http://api.controlasistenciasexto/estudiantes/1

### Modificar Estudiante
PUT http://api.controlasistenciasexto/estudiantes/1
Content-Type: application/json

{
  "nombre":"Juan",
  "apellido":"Perez",
  "direccion":"Calle Falsa 123",
  "telefono":"70011111"
}

### Adicionar Estudiante
POST http://api.controlasistenciasexto/estudiantes
Content-Type: application/json

{
  "nombre":"Maria",
  "apellido":"Gonzalez",
  "direccion":"Barrio Norte",
  "telefono":"70022222"
}

### Eliminar Estudiante
DELETE http://api.controlasistenciasexto/estudiantes/1
