### Consulta de inscripciones
GET http://api.controlasistenciasexto/inscripciones

### Consulta de inscripcion por id
GET http://api.controlasistenciasexto/inscripciones/1

### Modificar inscripcion
PUT http://api.controlasistenciasexto/inscripciones/1
Content-Type: application/json

{
	"cod_estudiante": 1,
	"cod_curso": 1,
	"gestion": 2026
}

### Adicionar inscripcion
POST http://api.controlasistenciasexto/inscripciones
Content-Type: application/json

{
	"cod_estudiante": 1,
	"cod_curso": 1,
	"gestion": 2026
}

### Eliminar inscripcion
DELETE http://api.controlasistenciasexto/inscripciones/1