### Consulta de materias
GET http://api.controlasistenciasexto/materias

### Consulta de materia por id
GET http://api.controlasistenciasexto/materias/1

### Modificar materia
PUT http://api.controlasistenciasexto/materias/1
Content-Type: application/json

{
	"nombre_materia": "Matemáticas"
}

### Adicionar materia
POST http://api.controlasistenciasexto/materias
Content-Type: application/json

{
	"nombre_materia": "Ciencias Naturales"
}

### Eliminar materia
DELETE http://api.controlasistenciasexto/materias/1