### Consulta de usuario
GET http://api.controlasistenciasexto/users

### Consulta de usuario por id
GET http://api.controlasistenciasexto/users/1

### Modificar Usuario
PUT http://api.controlasistenciasexto/users/1
Content-Type: application/json

{
  "username": "mquispe2",
  "password_hash": "$2y$10$hash_de_ejemplo2",
  "id_docente": 1,
  "id_estudiante": null
}

### Adicionar Usuario
POST http://api.controlasistenciasexto/users
Content-Type: application/json

{
  "username": "admin22",
  "password_hash": "$2y$10$hash_de_ejemplo",
  "id_docente": null,
  "id_estudiante": null
}

### Eliminar Usuario
DELETE http://api.controlasistenciasexto/users/1

